-- MySQL Script generated by MySQL Workbench
-- Thu Oct 24 22:07:03 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `documento` VARCHAR(20) NOT NULL,
  `tipo_cliente` CHAR(1) NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `documento_UNIQUE` (`documento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`conteiner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`conteiner` (
  `idconteiner` VARCHAR(11) NOT NULL,
  `tipo_conteiner` INT NOT NULL,
  `status` CHAR(1) NOT NULL,
  `categoria` CHAR(1) NULL,
  PRIMARY KEY (`idconteiner`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente_conteiner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente_conteiner` (
  `cliente_idcliente` INT NOT NULL,
  `conteiner_idconteiner` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`cliente_idcliente`, `conteiner_idconteiner`),
  INDEX `fk_cliente_conteiner_conteiner1_idx` (`conteiner_idconteiner` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_conteiner_cliente`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_conteiner_conteiner1`
    FOREIGN KEY (`conteiner_idconteiner`)
    REFERENCES `mydb`.`conteiner` (`idconteiner`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contato` (
  `idcontato` INT NOT NULL,
  `celular` VARCHAR(20) NULL,
  `telefone` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idcontato`, `cliente_idcliente`),
  INDEX `fk_contato_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_contato_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endereco` (
  `idendereco` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(255) NULL,
  `bairro` VARCHAR(255) NULL,
  `cidade` VARCHAR(255) NULL,
  `estado` VARCHAR(255) NULL,
  `cep` VARCHAR(10) NULL,
  `numero` INT NULL,
  `cliente_idcliente` INT NOT NULL,
  PRIMARY KEY (`idendereco`, `cliente_idcliente`),
  INDEX `fk_endereco_cliente1_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_cliente1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `mydb`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`movimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`movimentacao` (
  `idmovimentacao` INT NOT NULL,
  `tipo_movimentacao` VARCHAR(20) NOT NULL,
  `data_inicio` DATE NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `data_fim` DATE NULL,
  `hora_fim` TIME NULL,
  `conteiner_idconteiner` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idmovimentacao`, `conteiner_idconteiner`),
  INDEX `fk_movimentacao_conteiner1_idx` (`conteiner_idconteiner` ASC) VISIBLE,
  CONSTRAINT `fk_movimentacao_conteiner1`
    FOREIGN KEY (`conteiner_idconteiner`)
    REFERENCES `mydb`.`conteiner` (`idconteiner`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
